# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160715_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Kind', 'verbose_name_plural': 'Kinds'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('priority', 'pk'), 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
