# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_size_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='store',
        ),
        migrations.AddField(
            model_name='commodity',
            name='color_extra',
            field=models.CharField(blank=True, help_text='Useful if vendor did not find required color', max_length=50, verbose_name='Extra color'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='color_pic',
            field=models.ImageField(blank=True, null=True, upload_to='colors', verbose_name='Sample of color'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Color', verbose_name='Color'),
        ),
    ]
