# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160725_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to=utils.utils.UploadPath('gallery', 'commodity'), validators=[utils.validators.SizeValidator(15)], verbose_name='Photo'),
        ),
    ]
