# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160725_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='crop',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('gallery/crops', 'commodity', suff='crop'), verbose_name='Cropped photo'),
        ),
    ]
