# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_gallery_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Category'),
        ),
    ]
