# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_size_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_extra', models.CharField(blank=True, help_text='Useful if vendor did not find required color', max_length=50, verbose_name='Extra color')),
                ('color_pic', models.ImageField(blank=True, null=True, upload_to='colors', verbose_name='Sample of color')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Color', verbose_name='Color')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='color',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='color_extra',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='color_pic',
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='size',
        ),
        migrations.AddField(
            model_name='stock',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Commodity', verbose_name='Commodity'),
        ),
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Size', verbose_name='Size'),
        ),
    ]
