# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160901_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='colors',
            field=models.ManyToManyField(through='catalog.Stock', to='catalog.Color', verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='sizes',
            field=models.ManyToManyField(through='catalog.Stock', to='catalog.Size', verbose_name='Sizes'),
        ),
    ]
