# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20160901_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('commodity', 'color', 'size')]),
        ),
    ]
