# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160902_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
