# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20160908_1144'),
        ('catalog', '0013_commodity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50, verbose_name='Event Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Store', verbose_name='Store')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('post', models.ImageField(blank=True, null=True, upload_to='promotions', verbose_name='Post')),
                ('description', models.TextField(verbose_name='Description')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Store', verbose_name='Store')),
            ],
        ),
    ]
