# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_event_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ('-id',)},
        ),
    ]
