# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20160908_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',)},
        ),
    ]
