# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20160908_2215'),
        ('catalog', '0014_gallery_cover'),
    ]

    operations = [
    ]
