# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.utils
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitor', '0002_visitor_weixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='Longitude')),
                ('token', models.CharField(max_length=200, verbose_name='Device tokens')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('lock_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date locked')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Locked')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last login')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Mirror`s owner')),
            ],
            options={
                'ordering': ('-modify_date',),
                'verbose_name': 'Mirror',
                'verbose_name_plural': 'Mirrors',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Session id')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('mirror/photo', 'mirror'), validators=[utils.validators.SizeValidator(2)], verbose_name='Photo')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('mirror/photo/thumbs', 'mirror', suff='thumb'), verbose_name='Thumbnail')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modify_data', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Mirror', verbose_name='Mirror')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Mirror`s owner')),
            ],
            options={
                'ordering': ('create_date', 'id'),
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
