# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0002_auto_20160609_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='session',
        ),
    ]
