# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0003_remove_photo_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('mirror/photo', None, 'owner'), validators=[utils.validators.SizeValidator(2)], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('mirror/photo/thumbs', None, 'thumb', 'owner'), verbose_name='Thumbnail'),
        ),
    ]
