# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0004_auto_20160609_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
