# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0005_auto_20160609_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modify_data',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='modify_data',
            new_name='modify_date',
        ),
    ]
