# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0006_auto_20160610_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='token',
            field=models.CharField(max_length=200, unique=True, verbose_name='Device tokens'),
        ),
    ]
