# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0007_auto_20160612_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=10, max_digits=19, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mirror',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=10, max_digits=19, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
