# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20160614_2212'),
        ('snapshot', '0008_auto_20160613_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Description')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Group owner')),
            ],
            options={
                'ordering': ('create_date', 'pk'),
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Group', verbose_name='Group')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Group')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Group tag',
                'verbose_name_plural': 'Group tags',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(to='snapshot.Tag', verbose_name='Tags'),
        ),
    ]
