# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0009_auto_20160615_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snapshot.Group'),
        ),
    ]
