# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0010_photo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, to='snapshot.Tag', verbose_name='Tags'),
        ),
    ]
