# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0012_group_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snapshot.Group', verbose_name='Group'),
            preserve_default=False,
        ),
    ]
