# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20160614_2212'),
        ('snapshot', '0013_auto_20160616_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('pk',), 'verbose_name': 'Collaborator', 'verbose_name_plural': 'Collaborators'},
        ),
        migrations.AddField(
            model_name='tag',
            name='visitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Group'),
            preserve_default=False,
        ),
    ]
