# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0015_auto_20160617_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='mirror',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snapshot.Mirror', verbose_name='Mirror'),
        ),
    ]
