# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0017_auto_20160617_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('mirror/photo', None, 'visitor'), validators=[utils.validators.SizeValidator(2)], verbose_name='Photo'),
        ),
    ]
