# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0019_auto_20160617_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/group/thumbs', None, 'thumb', 'owner'), verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/group', 'title', 'owner'), validators=[utils.validators.SizeValidator(2)], verbose_name='Group avatar'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/photo', None, 'visitor'), validators=[utils.validators.SizeValidator(2)], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/photo/thumbs', None, 'thumb', 'visitor'), verbose_name='Thumbnail'),
        ),
    ]
