# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0023_auto_20160621_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/photo/crops', None, 'crop', 'visitor'), verbose_name='Cover'),
        ),
    ]
