# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0024_photo_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='group',
            name='thumb',
        ),
    ]
