# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0025_auto_20160627_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Like counter'),
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Like counter'),
        ),
    ]
