# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0027_auto_20160630_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snapshot.Group'),
        ),
    ]
