# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0028_auto_20160702_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.UploadPath('snapshot/photo/cover', None, 'cover', 'visitor'), verbose_name='Cover'),
        ),
    ]
