# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20160705_2021'),
        ('snapshot', '0029_auto_20160704_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='visitor.Visitor', verbose_name='Photo creator'),
        ),
        migrations.AddField(
            model_name='photo',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clones', related_query_name='clone', to='snapshot.Photo', verbose_name='Original'),
        ),
    ]
