# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0030_auto_20160705_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snapshot.Group'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', related_query_name='clone', to='snapshot.Photo', verbose_name='Original'),
        ),
    ]
