# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20160705_2021'),
        ('snapshot', '0031_auto_20160707_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Photo', verbose_name='Photo Likes'),
        ),
        migrations.AddField(
            model_name='like',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor', verbose_name='Visitor'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('photo', 'visitor')]),
        ),
    ]
