# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0035_photo_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='commodity',
        ),
    ]
