# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_gallery_crop'),
        ('snapshot', '0036_remove_photo_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Commodity', verbose_name='Commodity')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Photo', verbose_name='Photo')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Commodity Link',
                'verbose_name_plural': 'Commodity Links',
            },
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Photo', verbose_name='Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('photo', 'commodity')]),
        ),
    ]
