# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0038_auto_20160803_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='stamps',
            field=models.ManyToManyField(blank=True, through='snapshot.PhotoStamp', to='snapshot.Stamp'),
        ),
    ]
