# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0040_auto_20160803_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photostamp',
            options={'ordering': ('-confidence', 'pk'), 'verbose_name': 'Photo stamp', 'verbose_name_plural': 'Photo stamps'},
        ),
    ]
