# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snapshot', '0041_auto_20160808_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_groups', related_query_name='follow_group', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshot.Group', verbose_name='Group')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'Group Follower',
                'verbose_name_plural': 'Group Followers',
            },
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_users', related_query_name='follow_user', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name': 'User Follower',
                'verbose_name_plural': 'User Followers',
            },
        ),
    ]
