# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0043_auto_20160819_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snapshot.Article'),
        ),
    ]
