# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0044_auto_20160820_1446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followgroup',
            unique_together=set([('group', 'follower')]),
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together=set([('user', 'follower')]),
        ),
    ]
