# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0045_auto_20160822_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='followgroup',
            name='follow_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 24, 12, 59, 7, 228636, tzinfo=utc), verbose_name='Date Started Following'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followuser',
            name='follow_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 24, 12, 59, 13, 593397, tzinfo=utc), verbose_name='Date Started Following'),
            preserve_default=False,
        ),
    ]
