# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0046_auto_20160824_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 24, 17, 8, 8, 36071, tzinfo=utc), verbose_name='Date Started Like'),
            preserve_default=False,
        ),
    ]
