# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0048_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('pk',)},
        ),
    ]
