# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 07:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='visitors', validators=[utils.validators.SizeValidator(0.5)], verbose_name='Avatar')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='visitors/thumbs', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
        migrations.RenameField(
            model_name='store',
            old_name='logo',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/thumbs', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vendors', validators=[utils.validators.SizeValidator(0.5)], verbose_name='Avatar'),
        ),
    ]
