# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160527_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='stores/thumbs', verbose_name='Thumbnail'),
        ),
    ]
