# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_store_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='brand_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Brand name'),
        ),
    ]
