# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160711_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='thumb',
        ),
        migrations.AddField(
            model_name='store',
            name='crop',
            field=models.ImageField(blank=True, null=True, upload_to='stores/crops', verbose_name='Crop'),
        ),
    ]
