# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20160718_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be presented in international format including "+" and from 8 to 15 digits.', regex='^\\+\\d{9,16}$')], verbose_name='Phone'),
        ),
    ]
