# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 11:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=utils.fields.EmailNullField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=utils.fields.CharNullField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be presented in international format including "+" and from 8 to 15 digits.', regex='^\\+\\d{9,16}$')], verbose_name='Phone'),
        ),
    ]
