# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20160819_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default=123, max_length=150, verbose_name='Store name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='stores/post', verbose_name='Post'),
        ),
    ]
