# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20160909_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='apt',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Apartments'),
        ),
        migrations.AlterField(
            model_name='store',
            name='build_no',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Building number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street number'),
        ),
    ]
