# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20160909_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction of the store'),
        ),
    ]
