# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_store_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='brand_name',
            field=models.CharField(max_length=50, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Store name'),
        ),
    ]
