# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import visitor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='weixin',
            field=models.CharField(default='asdsdasddasdfgg', help_text='4-30 characters, Chinese and English letters, numbers, -, _', max_length=30, unique=True, validators=[visitor.validators.validate_weixin], verbose_name='Weixin id'),
            preserve_default=False,
        ),
    ]
