# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import visitor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_weixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='access_token',
            field=models.CharField(default='not set', max_length=255, verbose_name='Weixin Access Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='expires_in',
            field=models.IntegerField(default=1, verbose_name='Token expires in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='refresh_token',
            field=models.CharField(default='not set', max_length=255, verbose_name='Weixin Refresh Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='token_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Token date'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='weixin',
            field=models.CharField(help_text='4-30 characters, Chinese and English letters, numbers, -, _', max_length=30, unique=True, validators=[visitor.validators.validate_weixin], verbose_name='Weixin open id'),
        ),
    ]
