# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20160614_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='expires_in',
            field=models.PositiveIntegerField(verbose_name='Token expires in'),
        ),
    ]
