# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_auto_20160614_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='weixin',
            field=models.CharField(help_text='4-30 characters, Chinese and English letters, numbers, -, _', max_length=30, unique=True, validators=[utils.validators.validate_weixin], verbose_name='Weixin open id'),
        ),
    ]
