# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_auto_20160810_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='token_date',
        ),
    ]
