# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_remove_visitor_weixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='unionid',
            field=models.CharField(blank=True, db_index=True, help_text='For Weixin purpose only', max_length=40, verbose_name='Union ID'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='Username'),
        ),
    ]
