# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_auto_20160816_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weixin',
            fields=[
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='visitor.Visitor', verbose_name='visitor')),
                ('unionid', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Union ID')),
            ],
            options={
                'verbose_name': 'Weixin',
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be presented in international format including "+" and from 8 to 15 digits.', regex='^\\+\\d{9,16}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='unionid',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Union ID'),
        ),
    ]
