# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_auto_20160817_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorextra',
            name='weixin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Weixin', verbose_name='Weixin'),
        ),
        migrations.AlterUniqueTogether(
            name='visitorextra',
            unique_together=set([('weixin', 'backend'), ('visitor', 'backend')]),
        ),
    ]
