# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_auto_20160817_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='unionid',
        ),
    ]
