# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0014_remove_visitor_unionid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitorextra',
            unique_together=set([('weixin', 'backend')]),
        ),
    ]
