# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 10:26
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=utils.fields.EmailNullField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
