# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0018_auto_20160819_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=utils.fields.EmailNullField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be presented in international format including "+" and from 8 to 15 digits.', regex='^\\+\\d{9,16}$')], verbose_name='Phone'),
        ),
    ]
